site_name: Midnight Commander
site_url: https://new.midnight-commander.org
site_description: Midnight Commander Development Center

repo_name: MidnightCommander/mc
repo_url: https://github.com/MidnightCommander/mc/

extra:
  mirror_url: https://repo.or.cz/midnight-commander.git

copyright: Copyright &copy; 2025 Yury V. Zaytsev

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: img/mc-logo.png
  favicon: img/mc-logo.png

  palette:
    primary: custom
    accent: custom

  font:
    text: Fira Mono
    code: Fira Code

  features:
    - content.code.copy

nav:
  - Home: index.md
  - Development:
      - Source code: source-code.md
      - Translations: translations.md
      - Release process: release-process.md

plugins:
  - macros:
      on_undefined: strict
  - search

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      clickable_checkbox: true
