site_name: Midnight Commander
site_url: https://new.midnight-commander.org
site_description: Midnight Commander Development Center

repo_name: MidnightCommander/mc
repo_url: https://github.com/MidnightCommander/mc

extra:
  downloads_url: https://ftp.osuosl.org/pub/midnightcommander
  man_url: https://source.midnight-commander.org/man
  mirror_url: https://repo.or.cz/midnight-commander.git
  organization_url: https://github.com/MidnightCommander
  source_url: https://source.midnight-commander.org

copyright: Copyright &copy; 2025 <a href="https://www.linkedin.com/in/yuryzaytsev/">Yury V. Zaytsev</a>

extra_css:
  - stylesheets/extra.css

theme:
  language: en

  name: material
  logo: img/mc-logo.png
  favicon: img/mc-logo.png

  palette:
    primary: custom
    accent: custom

  font:
    text: Fira Mono
    code: Fira Code

  features:
    - content.code.copy
    - navigation.sections

nav:
  - Home: index.md
  - Maintainers: maintainers.md
  - Communication: communication.md
  - Other resources: other.md
  - Development:
      - Source code: source-code.md
      - Coding style: coding-style.md
      - Translations: translations.md
      - Release process: release-process.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true

plugins:
  - macros:
      on_undefined: strict
  - redirects:
      redirect_maps:
        'browser.md': https://github.com/MidnightCommander/mc/tree/master
        'diff.md': https://github.com/MidnightCommander/mc/commits/master
        'downloads.md': https://ftp.osuosl.org/pub/midnightcommander
        'log.md': https://github.com/MidnightCommander/mc/commits/master
        'milestone.md': https://github.com/MidnightCommander/mc/milestones
        'report.md': https://github.com/MidnightCommander/mc/issues
        'roadmap.md': https://github.com/MidnightCommander/mc/milestones
        'timeline.md': https://github.com/MidnightCommander/mc/commits/master
        'wiki.md': 'index.md'
  - search
