name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - run: uv sync --all-extras --dev

      - run: uv run mkdocs build
